// <auto-generated />
using System;
using CentroClinico.Infra.Banco.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CentroClinico.Infra.Banco.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("NumeroCartaoConvenio")
                        .HasColumnType("longtext");

                    b.Property<string>("Operadora")
                        .HasColumnType("longtext");

                    b.Property<string>("Plano")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Consulta", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MedicoID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UnidadeID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("MedicoID");

                    b.HasIndex("UnidadeID");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Consultorio", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Andar")
                        .HasColumnType("int");

                    b.Property<int>("Sala")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadeID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("UnidadeID");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Especialidade", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Funcionario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroEndereco")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Medico", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("CRM")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UnidadeID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("UnidadeID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.MedicoEspecialidade", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EspecialidadeID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MedicoID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("EspecialidadeID");

                    b.HasIndex("MedicoID");

                    b.ToTable("MedicoEspecialidades");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.MedicoUnidade", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MedicoID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UnidadeID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("MedicoID");

                    b.HasIndex("UnidadeID");

                    b.ToTable("MedicoUnidades");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Unidade", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Cliente", b =>
                {
                    b.HasOne("CentroClinico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Consulta", b =>
                {
                    b.HasOne("CentroClinico.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroClinico.Dominio.Entidades.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroClinico.Dominio.Entidades.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Medico");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Consultorio", b =>
                {
                    b.HasOne("CentroClinico.Dominio.Entidades.Unidade", "Unidade")
                        .WithMany("Consultorios")
                        .HasForeignKey("UnidadeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Funcionario", b =>
                {
                    b.HasOne("CentroClinico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Medico", b =>
                {
                    b.HasOne("CentroClinico.Dominio.Entidades.Unidade", null)
                        .WithMany("Medicos")
                        .HasForeignKey("UnidadeID");

                    b.HasOne("CentroClinico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.MedicoEspecialidade", b =>
                {
                    b.HasOne("CentroClinico.Dominio.Entidades.Especialidade", "Especialidade")
                        .WithMany("Medicos")
                        .HasForeignKey("EspecialidadeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroClinico.Dominio.Entidades.Medico", "Medico")
                        .WithMany("Especialidades")
                        .HasForeignKey("MedicoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.MedicoUnidade", b =>
                {
                    b.HasOne("CentroClinico.Dominio.Entidades.Medico", "Medico")
                        .WithMany("Unidades")
                        .HasForeignKey("MedicoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroClinico.Dominio.Entidades.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Especialidade", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Medico", b =>
                {
                    b.Navigation("Especialidades");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("CentroClinico.Dominio.Entidades.Unidade", b =>
                {
                    b.Navigation("Consultorios");

                    b.Navigation("Medicos");
                });
#pragma warning restore 612, 618
        }
    }
}
